name: terraform validate
on:
  - pull_request
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: terraform init
        run: terraform init -input=false -backend=false
      - uses: bendrucker/terraform-configuration-aliases-action@v1
      - name: terraform validate
        run: terraform validate
