name: terraform format check
on:
  - pull_request
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: terraform fmt
        run: terraform fmt -check -recursive -diff
